# Generated by Django 2.2.10 on 2020-03-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiview_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='enam',
            new_name='ename',
        ),
    ]
